### ISSUE TITLE
Windows audio service takes more cpu usage than before...

### ISSUE THREAD

**Issue by ANULAL2020** [AlanFinotty1995/AAF_DCH_RealtekModded#21]
Windows audio service is running with more cpu usage than before... I is running continuously in background with cpu usage in the absence of audio.. CPU usage is not too high... but the service  is continuously running unnecessary.. as shown  in  screenshot.. please look...
![Screenshot (30)](https://user-images.githubusercontent.com/64322146/92136032-2a5c8e00-ee29-11ea-9d76-c8d71d041a04.png)

**Comment by AlanFinotty1995** [comment]
The **Windows Audio service**, by default, runs automatically and continuously. The process that runs alternately is **audiodg.exe (Windows Audio Device Graphics Isolation).**

**Comment by ANULAL2020** [comment]
Oh . Thanks for your reply, But still I have some doubts about it ,so please review about its priority. 
THANKS FOR release the REALTEK HD AUDIO desktop version.. with amazing sound quality... But i am disappointed with the nahimic service... nahimic service is not optimised by their deveopers... so this service is using more cpu with 3 process. so i disabled this service .. If you can solve the over use of cpu by nahimic service solve this please ...
