### ISSUE TITLE
No audio effects with this version.

### ISSUE THREAD

**Issue by RCCore** [AlanFinotty1995/AAF_DCH_RealtekModded#3]
Well, I have moved from the legacy version to the DCH version and this version has no effect working, that is the only reason for me to keep the legacy version, I like the new modern interface of this apps but no effects working.

**Comment by AlanFinotty1995** [comment]
Access [**this link**](https://www.techpowerup.com/forums/threads/realtek-modded-audio-driver-for-windows-7-8-1-10-introducing-dch-version.250915/) and follow the "**(MANDATORY) FOLLOW THESE STEPS (ONLY IN DCH-UAD VERSION)**"spoiler instructions

**Comment by RCCore** [comment]
And I have another problem with the legacy one, the sound radar 3 is not working, It opens, then it crashes, and when I open it multiple times I see an error screen with a TIMEOUT message in it.

**Comment by AlanFinotty1995** [comment]
Type Windows + R on your keyboard, type "services.msc" without the quotes, look for Nahimic service and start it.

**Comment by RCCore** [comment]
Ammm, the Nahimic service is stopping when I open the Sonic Radar 3.

**Comment by ANULAL2020** [comment]
@RCCore Does the latest version solve this issue.

**Comment by RCCore** [comment]
Yes

**Comment by RCCore** [comment]
@ANULAL2020 I have used the patch for the effects
