### ISSUE TITLE
cant install the latest version..AAFAudioPackDCH-6.0.9008.1

### ISSUE THREAD

**Issue by ANULAL2020** [AlanFinotty1995/AAF_DCH_RealtekModded#30]
I downloaded this setup file, but the fie is not opening... NO any popup is coming...can you check this problem..
WINDOWS 10 1909  ALC 887 AUDIO CODEC

**Comment by ANULAL2020** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/64322146/92501814-a8030e00-f21c-11ea-83f8-eb2f8d1943c1.png)
This was the error shown by this file...  But i now understand that my avast antivirus was blocking this app by considering this file as virus....After the checking of file the setup file open normally..
I have one doubt alan ..why this file became a doubtful one to avast antivirus app...IS it contain any wrong records..

**Comment by RCCore** [comment]
@ANULAL2020, the file is safe you can scan with Virustotal, Avast shows this file as a virus because, its a false positive...(any antivirus can make mistakes).
